package com.example.model

enum class ApkAppType(val displayName: String, val description: String) {
    NATIVE_COMPOSE(
        displayName = "Native Jetpack Compose UI",
        description = "Compiles code logic into modern reactive Material 3 Android UI with ViewModels and Coroutines"
    ),
    HYBRID_WEBVIEW(
        displayName = "Hybrid WebView Container",
        description = "Packages HTML/JavaScript/Web code into a hardware-accelerated Android WebView with native JS Bridge"
    ),
    BACKGROUND_WORKER(
        displayName = "Android Service & WorkManager",
        description = "Runs code logic in a reliable background service and periodic WorkManager tasks"
    ),
    REST_API_CLIENT(
        displayName = "Mobile API Client & Repository",
        description = "Generates Retrofit/Ktor networking client, data models, and caching layers for mobile consumption"
    )
}

enum class ApkBuildStatus {
    IDLE,
    PARSING_SOURCE,
    GENERATING_COMPOSE_UI,
    CONFIGURING_MANIFEST_GRADLE,
    COMPILING_BYTECODE,
    DEXING_R8,
    ALIGNING_ZIP,
    SIGNING_APK,
    SUCCESS,
    FAILED
}

data class ApkConfig(
    val appName: String = "NationWide App",
    val packageName: String = "com.nationwide.app",
    val versionName: String = "1.0.0",
    val versionCode: Int = 1,
    val minSdk: Int = 24,
    val targetSdk: Int = 34,
    val appType: ApkAppType = ApkAppType.NATIVE_COMPOSE,
    val primaryColorHex: String = "#00F0FF",
    val secondaryColorHex: String = "#0284C7",
    val permissions: List<String> = listOf(
        "android.permission.INTERNET",
        "android.permission.ACCESS_NETWORK_STATE",
        "android.permission.POST_NOTIFICATIONS",
        "android.permission.VIBRATE"
    ),
    val enableDynamicColor: Boolean = true,
    val isHardwareAccelerated: Boolean = true,
    val appIconSymbol: String = "code", // code, rocket, phone, bolt, terminal
    val author: String = "NationWide Studio",
    val description: String = "Production Android application generated by NationWide Studio"
)

data class ApkBuildLogEntry(
    val timestamp: Long = System.currentTimeMillis(),
    val step: String,
    val message: String,
    val isError: Boolean = false
)

data class GeneratedApkProject(
    val config: ApkConfig,
    val mainActivityCode: String,
    val composeUiCode: String,
    val viewModelCode: String,
    val manifestXml: String,
    val buildGradleKts: String,
    val settingsGradleKts: String,
    val stringsXml: String,
    val colorsXml: String,
    val themesXml: String,
    val proguardRules: String,
    val allFiles: Map<String, String>,
    val apkSizeFormatted: String = "14.6 MB",
    val apkFileName: String = "NationWideApp-1.0.0-debug.apk",
    val sha256Digest: String = "d4e28f7a6c9b3105e1928374a5f6e7d8c9b0a1f2e3d4c5b6a7b8c9d0e1f2a3b4",
    val timestamp: Long = System.currentTimeMillis()
)
